#!/usr/bin/env python3
"""Generate the heart-from-centre G-code program for the ME306 CoreXY plotter.

Firmware constraints this generator has to respect (see src/GCodeParser.cpp):

  * X / Y / F are parsed as INTEGERS. A decimal point is rejected outright,
    so every emitted number must be a whole mm / mm-min value.
  * G1 requires BOTH X and Y on the line, or the line is rejected.
  * G1 targets are RELATIVE. G1::beginMove() zeroes the encoders on every
    move and treats X/Y as a displacement from wherever the pen is now.
  * A G1 with a zero displacement (X0 Y0) never completes: pathLength_ is 0
    so the profile's `s_` can never reach 1.0 and the FSM hangs in G1. Any
    waypoint that rounds onto its predecessor must therefore be dropped.
  * F is sticky (inherited between lines) but must appear on the first move.

To stop integer rounding from accumulating around the outline, absolute
waypoints are rounded to whole mm FIRST and the relative deltas are then
taken between the rounded absolutes. Error stays bounded at +/- 0.5 mm
instead of drifting.
"""

import argparse
import math

# Classic parametric heart.
def heart(t):
    x = 16.0 * math.sin(t) ** 3
    y = (13.0 * math.cos(t)
         - 5.0 * math.cos(2.0 * t)
         - 2.0 * math.cos(3.0 * t)
         - math.cos(4.0 * t))
    return x, y


def resample_by_arclength(t0, t1, n_out, n_dense=4000):
    """Sample the curve at `n_out` points spaced evenly by ARC LENGTH.

    Sampling evenly in `t` bunches the points up around the cusp and the
    lobes. The plotter comes to a full stop at every waypoint, so uneven
    spacing shows up directly as uneven drawing speed.
    """
    ts = [t0 + (t1 - t0) * i / n_dense for i in range(n_dense + 1)]
    pts = [heart(t) for t in ts]

    cum = [0.0]
    for i in range(1, len(pts)):
        dx = pts[i][0] - pts[i - 1][0]
        dy = pts[i][1] - pts[i - 1][1]
        cum.append(cum[-1] + math.hypot(dx, dy))
    total = cum[-1]

    out = []
    j = 0
    for i in range(n_out + 1):
        target = total * i / n_out
        while j < len(cum) - 1 and cum[j + 1] < target:
            j += 1
        # Linear interpolation between the two bracketing dense samples.
        span = cum[j + 1] - cum[j]
        frac = 0.0 if span <= 0.0 else (target - cum[j]) / span
        x = pts[j][0] + (pts[j + 1][0] - pts[j][0]) * frac
        y = pts[j][1] + (pts[j + 1][1] - pts[j][1]) * frac
        out.append((x, y))
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--centre-x", type=float, default=100.0)
    ap.add_argument("--centre-y", type=float, default=100.0)
    ap.add_argument("--scale", type=float, default=2.5,
                    help="multiplier on the unit heart (~32 x 29 units)")
    ap.add_argument("--segments", type=int, default=40)
    ap.add_argument("--feed", type=int, default=600, help="mm/min")
    ap.add_argument("--x-max", type=float, default=200.0)
    ap.add_argument("--y-max", type=float, default=200.0)
    ap.add_argument("-o", "--out", default="tools/heart.gcode")
    args = ap.parse_args()

    # Trace the outline starting and ending at the bottom cusp (t = pi), so
    # the pen enters and leaves the outline on the heart's axis of symmetry.
    raw = resample_by_arclength(math.pi, 3.0 * math.pi, args.segments)

    ys = [p[1] for p in raw]
    y_mid = (max(ys) + min(ys)) / 2.0   # centre the BOUNDING BOX, not t=0

    def to_machine(p):
        return (args.centre_x + args.scale * p[0],
                args.centre_y + args.scale * (p[1] - y_mid))

    outline = [to_machine(p) for p in raw]

    centre = (args.centre_x, args.centre_y)
    # Centre -> bottom cusp -> around the outline -> bottom cusp -> centre.
    # The lead-in and lead-out both run down the x = centre_x axis of
    # symmetry, so the return stroke retraces the entry stroke exactly and
    # only one line is visible through the middle of the heart.
    path = [centre] + outline + [centre]

    # Round to whole mm first, then difference: bounded error, no drift.
    abs_pts = [(round(x), round(y)) for x, y in path]

    for x, y in abs_pts:
        if not (0 <= x <= args.x_max and 0 <= y <= args.y_max):
            raise SystemExit(
                f"waypoint ({x}, {y}) is outside the {args.x_max:.0f} x "
                f"{args.y_max:.0f} mm envelope - reduce --scale or move the centre")

    lines = []
    lines.append("; Heart from centre - ME306 CoreXY plotter")
    lines.append("; Generated by tools/gen_heart.py - do not hand-edit.")
    lines.append(f"; scale={args.scale} segments={args.segments} feed={args.feed} mm/min")
    lines.append(f"; centred on ({args.centre_x:.0f}, {args.centre_y:.0f}) mm")
    w = max(x for x, _ in abs_pts) - min(x for x, _ in abs_pts)
    h = max(y for _, y in abs_pts) - min(y for _, y in abs_pts)
    lines.append(f"; outline bounding box {w} x {h} mm")
    lines.append(";")
    lines.append("; All G1 moves are RELATIVE (see G1::beginMove).")
    lines.append(";")
    lines.append("; Home first: seeks LEFT then BOTTOM and zeroes the origin there.")
    lines.append("G28")
    lines.append(";")
    lines.append("; Travel from the home corner out to the centre. The firmware has")
    lines.append("; no pen lift, so this leaves a visible lead-in line.")

    cur = (0, 0)
    first_move = True
    dropped = 0

    for i, pt in enumerate(abs_pts):
        dx = pt[0] - cur[0]
        dy = pt[1] - cur[1]
        if dx == 0 and dy == 0:
            dropped += 1          # would hang the FSM; skip it
            continue
        if first_move:
            lines.append(f"G1 X{dx} Y{dy} F{args.feed}")
            first_move = False
        else:
            lines.append(f"G1 X{dx} Y{dy}")
        cur = pt
        if i == 0:
            lines.append("; --- at centre: draw the heart from here ---")

    lines.append("; Back at the centre.")

    text = "\n".join(lines) + "\n"
    with open(args.out, "w") as f:
        f.write(text)

    n_moves = sum(1 for line in lines if line.startswith("G1"))
    print(f"wrote {args.out}: {n_moves} G1 moves, "
          f"{dropped} zero-length waypoint(s) dropped")
    print(f"outline bounding box {w} x {h} mm, centred on "
          f"({args.centre_x:.0f}, {args.centre_y:.0f})")
    print(f"end position: ({cur[0]}, {cur[1]}) mm")


if __name__ == "__main__":
    main()
